In [1]:
import pandas as  pd
import tensorflow as tf
from keras.preprocessing.text import Tokenizer
import numpy as np

from sklearn.model_selection import train_test_split


In [2]:
df=pd.read_csv(r"C:\Users\Admin\Downloads\Deep Learning\IMDB Dataset.csv")

In [3]:
import string
print(string.punctuation)

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


In [4]:
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [5]:
df['review'][1]

'A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. <br /><br />The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well d

In [6]:
def lowercase(str):
    sentence=str.lower()
    return sentence
df['review']=df['review'].apply(lowercase)
    

In [7]:
def removepuntuation(str):
    str=str.replace("<br />","")
    text_p = "".join([char for char in str if char not in string.punctuation])
    return text_p
df['review']=df['review'].apply(removepuntuation)

In [8]:
X=df['review']
y=df['sentiment']

In [9]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,stratify=y)

In [10]:
X_train.shape,X_test.shape

((40000,), (10000,))

In [11]:
X_train

18019    imdb lists this movie as a comedy i have no id...
34313    theres only one thing im going to say about ca...
13472    i heard and read many praising things about mi...
6349     this is a movie about animal cruelty under the...
39333    i like the film it´s the best piratemovie i wa...
                               ...                        
33957    i am normally skeptical about watching films o...
34254    this film is truly execrable in all department...
20458    the fine cast cannot uplift this routine tale ...
30006    was curious to know the name of the tuscan vil...
35872    i watched this series on pbs back in the eight...
Name: review, Length: 40000, dtype: object

In [12]:
tokenizer=Tokenizer(num_words=600)
tokenizer.fit_on_texts(X_train)
X_train=tokenizer.texts_to_sequences(X_train)
X_test=tokenizer.texts_to_sequences(X_test)
vocab_size=len(tokenizer.word_index)+1

In [13]:
from tensorflow.keras.utils import pad_sequences
X_train=pad_sequences(X_train,padding="post",maxlen=1465)
X_test=pad_sequences(X_test,padding="post",maxlen=1465)

In [14]:
y_train=np.where(y_train=='negative',0,1)
y_test=np.where(y_test=='negative',0,1)

In [15]:
y_train

array([0, 0, 0, ..., 0, 1, 1])

In [16]:
from keras.utils import to_categorical
num_classess=2
y_train=to_categorical(y_train,num_classess)
y_test=to_categorical(y_test,num_classess)

In [17]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, SimpleRNN,Dropout,Activation
from tensorflow.keras.optimizers import Adam


In [18]:
X_train=X_train.reshape(X_train.shape[0],X_train.shape[1],1)
X_test=X_test.reshape(X_test.shape[0],X_test.shape[1],1)

In [19]:
X_train.shape

(40000, 1465, 1)

In [20]:
X_test.shape

(10000, 1465, 1)

In [41]:
model=Sequential()
model.add(SimpleRNN(64,input_shape=(1465,1),return_sequences=True))
model.add(SimpleRNN(32,input_shape=(None,64)))
model.add(Dense(2,activation='softmax'))
model.summary()
model.compile(loss="categorical_crossentropy",optimizer=adam,metrics=['accuracy'])

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_7 (SimpleRNN)    (None, 1465, 64)          4224      
                                                                 
 simple_rnn_8 (SimpleRNN)    (None, 32)                3104      
                                                                 
 dense_1 (Dense)             (None, 2)                 66        
                                                                 
Total params: 7,394
Trainable params: 7,394
Non-trainable params: 0
_________________________________________________________________


C:\Users\Admin\anaconda3\lib\site-packages\keras\optimizers\optimizer_v2\adam.py:114: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


In [43]:
model.fit(X_train,y_train,epochs=2,batch_size=64)

Epoch 1/2
625/625 [==============================] - 1907s 3s/step - loss: 0.6966 - accuracy: 0.5013
Epoch 2/2
625/625 [==============================] - 1995s 3s/step - loss: 0.6941 - accuracy: 0.4979


In [26]:
from sklearn.metrics import accuracy_score
y_predict=model.predict(X_test)


313/313 [==============================] - 70s 225ms/step


In [33]:
y_pred=np.argmax(y_predict,axis=1)

In [35]:
y_pred

array([0, 0, 0, ..., 1, 0, 0], dtype=int64)

In [37]:

print(accuracy_score(y_test,y_pred))

0.4983


In [29]:
y_predict

array([[0.52070004, 0.4793    ],
       [0.5207    , 0.47930002],
       [0.504286  , 0.49571404],
       ...,
       [0.48841557, 0.51158446],
       [0.52070004, 0.4793    ],
       [0.504286  , 0.49571404]], dtype=float32)